//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string MainPage_HealtKitAuthorization_Error_Button {
            get {
                return ResourceManager.GetString("MainPage_HealtKitAuthorization_Error_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. 😢
        ///
        ///We&apos;ll try to take a look at it..
        /// </summary>
        public static string MainPage_HealtKitAuthorization_Error_Message {
            get {
                return ResourceManager.GetString("MainPage_HealtKitAuthorization_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainPage_HealtKitAuthorization_Error_Title {
            get {
                return ResourceManager.GetString("MainPage_HealtKitAuthorization_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MainPage_HealtKitAuthorization_Success_Button {
            get {
                return ResourceManager.GetString("MainPage_HealtKitAuthorization_Success_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you did it! 👏.
        /// </summary>
        public static string MainPage_HealtKitAuthorization_Success_Message {
            get {
                return ResourceManager.GetString("MainPage_HealtKitAuthorization_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string MainPage_HealtKitAuthorization_Success_Title {
            get {
                return ResourceManager.GetString("MainPage_HealtKitAuthorization_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Settings_DurationUnit_Hours {
            get {
                return ResourceManager.GetString("Settings_DurationUnit_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Settings_DurationUnit_Minutes {
            get {
                return ResourceManager.GetString("Settings_DurationUnit_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string Settings_EnergyUnit_Calories {
            get {
                return ResourceManager.GetString("Settings_EnergyUnit_Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilocalories.
        /// </summary>
        public static string Settings_EnergyUnit_Kilocalories {
            get {
                return ResourceManager.GetString("Settings_EnergyUnit_Kilocalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Monthly Summaries.
        /// </summary>
        public static string Settings_ExcelExport_NumMonthlySummaries {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_NumMonthlySummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omit Empty Cols On Monthly Summary.
        /// </summary>
        public static string Settings_ExcelExport_OmitEmptyColumnsOnMonthly {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_OmitEmptyColumnsOnMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omit Empty Cols On Overall Summary.
        /// </summary>
        public static string Settings_ExcelExport_OmitEmptyColumnsOnOverall {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_OmitEmptyColumnsOnOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omit Empty Sheets.
        /// </summary>
        public static string Settings_ExcelExport_OmitEmptySheets {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_OmitEmptySheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❤️ Apple Health.
        /// </summary>
        public static string Settings_GettingStarted_AuthorizationStatusLabel {
            get {
                return ResourceManager.GetString("Settings_GettingStarted_AuthorizationStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Use Data Since.
        /// </summary>
        public static string Settings_GettingStarted_FetchSinceDateLabel {
            get {
                return ResourceManager.GetString("Settings_GettingStarted_FetchSinceDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Now.
        /// </summary>
        public static string Settings_IsAuthorizedButton_False {
            get {
                return ResourceManager.GetString("Settings_IsAuthorizedButton_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✔️ Connected.
        /// </summary>
        public static string Settings_IsAuthorizedButton_True {
            get {
                return ResourceManager.GetString("Settings_IsAuthorizedButton_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Settings_LengthUnit_Meters {
            get {
                return ResourceManager.GetString("Settings_LengthUnit_Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Settings_LengthUnit_Miles {
            get {
                return ResourceManager.GetString("Settings_LengthUnit_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        public static string Settings_MassUnit_Kilograms {
            get {
                return ResourceManager.GetString("Settings_MassUnit_Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        public static string Settings_MassUnit_Pounds {
            get {
                return ResourceManager.GetString("Settings_MassUnit_Pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export Settings.
        /// </summary>
        public static string Settings_Section_ExcelExportSettings {
            get {
                return ResourceManager.GetString("Settings_Section_ExcelExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string Settings_Section_GettingStarted {
            get {
                return ResourceManager.GetString("Settings_Section_GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units of Measurement.
        /// </summary>
        public static string Settings_Section_UnitsOfMeasure {
            get {
                return ResourceManager.GetString("Settings_Section_UnitsOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📏 Distance Unit.
        /// </summary>
        public static string Settings_UnitsOfMeasure_DistanceUnit {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_DistanceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱️ Duration Unit.
        /// </summary>
        public static string Settings_UnitsOfMeasure_DurationUnit {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_DurationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤤 Energy Unit.
        /// </summary>
        public static string Settings_UnitsOfMeasure_EnergyUnit {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_EnergyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚖️ Weight/Mass Unit.
        /// </summary>
        public static string Settings_UnitsOfMeasure_MassUnit {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_MassUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not set.
        /// </summary>
        public static string Settings_UnitsOfMeasure_NotSet {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_NotSet", resourceCulture);
            }
        }
    }
}
