//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string ExportSettings_CustomSheets_Change_Browse {
            get {
                return ResourceManager.GetString("ExportSettings_CustomSheets_Change_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ExportSettings_CustomSheets_Change_Cancel {
            get {
                return ResourceManager.GetString("ExportSettings_CustomSheets_Change_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear (Don&apos;t Use Custom Sheets).
        /// </summary>
        public static string ExportSettings_CustomSheets_Change_Clear {
            get {
                return ResourceManager.GetString("ExportSettings_CustomSheets_Change_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Custom Sheets Location.
        /// </summary>
        public static string ExportSettings_CustomSheets_Change_Title {
            get {
                return ResourceManager.GetString("ExportSettings_CustomSheets_Change_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        public static string ExportSettings_Title {
            get {
                return ResourceManager.GetString("ExportSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry.
        /// </summary>
        public static string HealtKitAuthorization_Error_Button {
            get {
                return ResourceManager.GetString("HealtKitAuthorization_Error_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. 😢
        ///
        ///We&apos;ll try to take a look at it..
        /// </summary>
        public static string HealtKitAuthorization_Error_Message {
            get {
                return ResourceManager.GetString("HealtKitAuthorization_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string HealtKitAuthorization_Error_Title {
            get {
                return ResourceManager.GetString("HealtKitAuthorization_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string HealtKitAuthorization_Success_Button {
            get {
                return ResourceManager.GetString("HealtKitAuthorization_Success_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you did it! 👏.
        /// </summary>
        public static string HealtKitAuthorization_Success_Message {
            get {
                return ResourceManager.GetString("HealtKitAuthorization_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string HealtKitAuthorization_Success_Title {
            get {
                return ResourceManager.GetString("HealtKitAuthorization_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grant HealthNerd Access.
        /// </summary>
        public static string MainPage_AuthorizeHealth_Button {
            get {
                return ResourceManager.GetString("MainPage_AuthorizeHealth_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 👋.
        /// </summary>
        public static string MainPage_AuthorizeHealth_Icon {
            get {
                return ResourceManager.GetString("MainPage_AuthorizeHealth_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First, we&apos;ll need to get access to your Health data..
        /// </summary>
        public static string MainPage_AuthorizeHealth_Text {
            get {
                return ResourceManager.GetString("MainPage_AuthorizeHealth_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s Get Started..
        /// </summary>
        public static string MainPage_AuthorizeHealth_Title {
            get {
                return ResourceManager.GetString("MainPage_AuthorizeHealth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Nerdery Setup 🗃️.
        /// </summary>
        public static string MainPage_FirstTimeSetup_Button {
            get {
                return ResourceManager.GetString("MainPage_FirstTimeSetup_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Spreadsheet.
        /// </summary>
        public static string MainPage_NerdOut_Button {
            get {
                return ResourceManager.GetString("MainPage_NerdOut_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤓.
        /// </summary>
        public static string MainPage_NerdOut_Icon {
            get {
                return ResourceManager.GetString("MainPage_NerdOut_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to Nerd Out!.
        /// </summary>
        public static string MainPage_NerdOut_Title {
            get {
                return ResourceManager.GetString("MainPage_NerdOut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shared file {0}.
        /// </summary>
        public static string MainPage_Status_Complete {
            get {
                return ResourceManager.GetString("MainPage_Status_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to an error occurred.
        /// </summary>
        public static string MainPage_Status_Error {
            get {
                return ResourceManager.GetString("MainPage_Status_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gathering data.
        /// </summary>
        public static string MainPage_Status_Gathering {
            get {
                return ResourceManager.GetString("MainPage_Status_Gathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to writing file.
        /// </summary>
        public static string MainPage_Status_SavingFile {
            get {
                return ResourceManager.GetString("MainPage_Status_SavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharing file.
        /// </summary>
        public static string MainPage_Status_SharingFile {
            get {
                return ResourceManager.GetString("MainPage_Status_SharingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Nerd.
        /// </summary>
        public static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚙️.
        /// </summary>
        public static string MainPage_ToolbarItem_Settings {
            get {
                return ResourceManager.GetString("MainPage_ToolbarItem_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to let HealthNerd read data out of Apple Health. HealthNerd will only be able to read the data you approve..
        /// </summary>
        public static string Onboarding_Auth_Body {
            get {
                return ResourceManager.GetString("Onboarding_Auth_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Now.
        /// </summary>
        public static string Onboarding_Auth_Button {
            get {
                return ResourceManager.GetString("Onboarding_Auth_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Apple Health.
        /// </summary>
        public static string Onboarding_Auth_Title {
            get {
                return ResourceManager.GetString("Onboarding_Auth_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Onboarding_Finish {
            get {
                return ResourceManager.GetString("Onboarding_Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re all set! Go ahead and continue being the nerd we both know you are..
        /// </summary>
        public static string Onboarding_Finish_Body {
            get {
                return ResourceManager.GetString("Onboarding_Finish_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Setup.
        /// </summary>
        public static string Onboarding_Finish_Button {
            get {
                return ResourceManager.GetString("Onboarding_Finish_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Nerdy With It!.
        /// </summary>
        public static string Onboarding_Finish_Title {
            get {
                return ResourceManager.GetString("Onboarding_Finish_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Onboarding_Next {
            get {
                return ResourceManager.GetString("Onboarding_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Onboarding_Previous {
            get {
                return ResourceManager.GetString("Onboarding_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Onboarding_Settings_Title {
            get {
                return ResourceManager.GetString("Onboarding_Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re the type of person that likes data. Let&apos;s get you all set up..
        /// </summary>
        public static string Onboarding_Welcome_Body {
            get {
                return ResourceManager.GetString("Onboarding_Welcome_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to HealthNerd!.
        /// </summary>
        public static string Onboarding_Welcome_Title {
            get {
                return ResourceManager.GetString("Onboarding_Welcome_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze your Health data your way.
        ///
        ///Convert your workout data, body measurements and more into a spreadsheet so you can nerd out to your ❤️&apos;s content..
        /// </summary>
        public static string Onboarding_What_Body {
            get {
                return ResourceManager.GetString("Onboarding_What_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Health-y Spreadsheet.
        /// </summary>
        public static string Onboarding_What_Title {
            get {
                return ResourceManager.GetString("Onboarding_What_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork by Justin Muse.
        /// </summary>
        public static string Settings_About_ArtworkBy {
            get {
                return ResourceManager.GetString("Settings_About_ArtworkBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @JM_Designz.
        /// </summary>
        public static string Settings_About_ArtworkBy_Detail {
            get {
                return ResourceManager.GetString("Settings_About_ArtworkBy_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made at SEP in Indiana.
        /// </summary>
        public static string Settings_About_MadeBy {
            get {
                return ResourceManager.GetString("Settings_About_MadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Settings_DurationUnit_Hours {
            get {
                return ResourceManager.GetString("Settings_DurationUnit_Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Settings_DurationUnit_Minutes {
            get {
                return ResourceManager.GetString("Settings_DurationUnit_Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        public static string Settings_EnergyUnit_Calories {
            get {
                return ResourceManager.GetString("Settings_EnergyUnit_Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilocalories.
        /// </summary>
        public static string Settings_EnergyUnit_Kilocalories {
            get {
                return ResourceManager.GetString("Settings_EnergyUnit_Kilocalories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Sheets.
        /// </summary>
        public static string Settings_ExcelExport_CustomSheets {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_CustomSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Monthly Summaries.
        /// </summary>
        public static string Settings_ExcelExport_NumMonthlySummaries {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_NumMonthlySummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omit Empty Cols On Monthly Summary.
        /// </summary>
        public static string Settings_ExcelExport_OmitEmptyColumnsOnMonthly {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_OmitEmptyColumnsOnMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omit Empty Cols On Overall Summary.
        /// </summary>
        public static string Settings_ExcelExport_OmitEmptyColumnsOnOverall {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_OmitEmptyColumnsOnOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omit Empty Sheets.
        /// </summary>
        public static string Settings_ExcelExport_OmitEmptySheets {
            get {
                return ResourceManager.GetString("Settings_ExcelExport_OmitEmptySheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Time Setup.
        /// </summary>
        public static string Settings_FirstTimeSetup {
            get {
                return ResourceManager.GetString("Settings_FirstTimeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❤️ Apple Health.
        /// </summary>
        public static string Settings_GettingStarted_AuthorizationStatusLabel {
            get {
                return ResourceManager.GetString("Settings_GettingStarted_AuthorizationStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤓 Data Output Settings.
        /// </summary>
        public static string Settings_GettingStarted_ExportSettingsLabel {
            get {
                return ResourceManager.GetString("Settings_GettingStarted_ExportSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📅 Use Data Since.
        /// </summary>
        public static string Settings_GettingStarted_FetchSinceDateLabel {
            get {
                return ResourceManager.GetString("Settings_GettingStarted_FetchSinceDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect Now.
        /// </summary>
        public static string Settings_IsAuthorizedButton_False {
            get {
                return ResourceManager.GetString("Settings_IsAuthorizedButton_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✓ Connected.
        /// </summary>
        public static string Settings_IsAuthorizedButton_True {
            get {
                return ResourceManager.GetString("Settings_IsAuthorizedButton_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meters.
        /// </summary>
        public static string Settings_LengthUnit_Meters {
            get {
                return ResourceManager.GetString("Settings_LengthUnit_Meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miles.
        /// </summary>
        public static string Settings_LengthUnit_Miles {
            get {
                return ResourceManager.GetString("Settings_LengthUnit_Miles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilograms.
        /// </summary>
        public static string Settings_MassUnit_Kilograms {
            get {
                return ResourceManager.GetString("Settings_MassUnit_Kilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pounds.
        /// </summary>
        public static string Settings_MassUnit_Pounds {
            get {
                return ResourceManager.GetString("Settings_MassUnit_Pounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Settings_Section_About {
            get {
                return ResourceManager.GetString("Settings_Section_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Export Settings.
        /// </summary>
        public static string Settings_Section_ExcelExportSettings {
            get {
                return ResourceManager.GetString("Settings_Section_ExcelExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Started.
        /// </summary>
        public static string Settings_Section_GettingStarted {
            get {
                return ResourceManager.GetString("Settings_Section_GettingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units of Measurement.
        /// </summary>
        public static string Settings_Section_UnitsOfMeasure {
            get {
                return ResourceManager.GetString("Settings_Section_UnitsOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📏 Distance Unit.
        /// </summary>
        public static string Settings_UnitsOfMeasure_DistanceUnit {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_DistanceUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⏱️ Duration Unit.
        /// </summary>
        public static string Settings_UnitsOfMeasure_DurationUnit {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_DurationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🤤 Energy Unit.
        /// </summary>
        public static string Settings_UnitsOfMeasure_EnergyUnit {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_EnergyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚖️ Weight/Mass Unit.
        /// </summary>
        public static string Settings_UnitsOfMeasure_MassUnit {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_MassUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not set.
        /// </summary>
        public static string Settings_UnitsOfMeasure_NotSet {
            get {
                return ResourceManager.GetString("Settings_UnitsOfMeasure_NotSet", resourceCulture);
            }
        }
    }
}
